name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm install -g pnpm@10.11.0
          pnpm install
          pnpm run build:packages

      # Upload build artifacts to be used by other jobs
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            packages/
            examples/
            !**/node_modules
  
  # Test job - runs in parallel with make-site
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Install dependencies
        run: |
          npm install -g pnpm@10.11.0
          pnpm install

      - name: Run tests
        run: |
          pnpm install -dw playwright
          npx playwright install --with-deps chromium
          CI=true pnpm run test

  # Make site job - runs in parallel with test
  make-site:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Build examples
        run: |
          npm install -g pnpm@10.11.0
          pnpm install
          pnpm run build:examples

      - name: Make site
        run: |
          rm -rf site || true
          mkdir -p site/examples
          for d in examples/*; do
            cp -r $d/dist site/examples/$(basename $d)
          done
          mv site/examples/main/* site/

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [test, make-site]
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4